import { promises as fs } from "node:fs";
import path from "node:path";

import { artifacts } from "hardhat";

/**
 * Writes the ABIs the frontend needs into a single generated module.
 *
 * Only the contracts the interface actually talks to, and only their ABIs —
 * bytecode and build metadata would add megabytes the browser never uses.
 * Generated rather than hand-copied so a contract change cannot silently
 * leave the frontend calling a signature that no longer exists.
 *
 *   npx hardhat run scripts/export-abi.ts
 */

const CONTRACTS = [
  "ConfidentialPrizePool",
  "DrawEngine",
  "PrizeVault",
  "TicketLedger",
  "DisclosureRegistry",
  "ConfidentialTokenMock",
  "TieredWeightPolicy",
] as const;

const OUT_FILE = path.join(__dirname, "..", "frontend", "lib", "abi.ts");

async function main(): Promise<void> {
  const entries: string[] = [];

  for (const name of CONTRACTS) {
    const artifact = await artifacts.readArtifact(name);
    entries.push(`  ${name}: ${JSON.stringify(artifact.abi)} as const,`);
  }

  const source =
    `// Generated by scripts/export-abi.ts — do not edit.\n` +
    `// Regenerate with: npx hardhat run scripts/export-abi.ts\n\n` +
    `export const ABI = {\n${entries.join("\n")}\n} as const;\n`;

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, source, "utf8");

  process.stdout.write(`Wrote ${CONTRACTS.length} ABIs to ${OUT_FILE}\n`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
